#!/usr/bin/env python3
"""
scripts/gen-python-types.py

Generates authoritative Pydantic v2 classes and Enums from `contracts/` JSON schemas into
`apps/api/schemas/generated/`.
"""

import json
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
CONTRACTS_DIR = ROOT_DIR / "contracts"
ENUMS_DIR = CONTRACTS_DIR / "enums"
EVENTS_DIR = CONTRACTS_DIR / "events"
OUT_DIR = ROOT_DIR / "apps" / "api" / "schemas" / "generated"

def load_json(filepath: Path) -> dict:
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)

def generate_enums():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_file = OUT_DIR / "enums.py"

    worker_event_types = load_json(ENUMS_DIR / "worker_event_type.json")["enum"]
    worker_states_data = load_json(ENUMS_DIR / "worker_state.json")
    worker_states = worker_states_data["enum"]
    state_transitions = worker_states_data.get("x-transitions", {})
    state_animation_map = worker_states_data.get("x-3d-animation-map", {})
    logical_zones = load_json(ENUMS_DIR / "logical_zone.json")["x-zone-enum"]
    worker_types_data = load_json(ENUMS_DIR / "worker_type.json")
    worker_types = worker_types_data["enum"]
    worker_type_zone_defaults = worker_types_data.get("x-zone-defaults", {})
    source_capabilities = load_json(ENUMS_DIR / "source_capability.json")["enum"]

    code = [
        '"""',
        'AUTOGENERATED FILE — DO NOT EDIT DIRECTLY',
        'Generated from contracts/enums/ by scripts/gen-python-types.py',
        '"""',
        '',
        'from enum import Enum',
        'from typing import Dict, List',
        '',
        'class WorkerEventType(str, Enum):',
    ]
    for et in worker_event_types:
        var_name = et.replace(".", "_").upper()
        code.append(f'    {var_name} = "{et}"')

    code.extend([
        '',
        'class WorkerState(str, Enum):',
    ])
    for st in worker_states:
        code.append(f'    {st} = "{st}"')

    code.extend([
        '',
        'class LogicalZone(str, Enum):',
    ])
    for lz in logical_zones:
        code.append(f'    {lz} = "{lz}"')

    code.extend([
        '',
        'class WorkerTypeEnum(str, Enum):',
    ])
    for wt in worker_types:
        var_name = wt.upper()
        code.append(f'    {var_name} = "{wt}"')

    code.extend([
        '',
        'class SourceCapability(str, Enum):',
    ])
    for sc in source_capabilities:
        code.append(f'    {sc} = "{sc}"')

    code.extend([
        '',
        '# Valid state transitions mapping: WorkerState -> List[WorkerState]',
        'WORKER_STATE_TRANSITIONS: Dict[WorkerState, List[WorkerState]] = {',
    ])
    for st, targets in state_transitions.items():
        targets_str = ", ".join([f'WorkerState.{t}' for t in targets])
        code.append(f'    WorkerState.{st}: [{targets_str}],')
    code.append('}')

    code.extend([
        '',
        '# 3D Animation identifiers for visual state machine',
        'WORKER_ANIMATION_MAP: Dict[WorkerState, str] = {',
    ])
    for st, anim in state_animation_map.items():
        code.append(f'    WorkerState.{st}: "{anim}",')
    code.append('}')

    code.extend([
        '',
        '# Default Zone assignments for each worker type',
        'WORKER_TYPE_DEFAULT_ZONES: Dict[WorkerTypeEnum, LogicalZone] = {',
    ])
    for wt, zone in worker_type_zone_defaults.items():
        code.append(f'    WorkerTypeEnum.{wt.upper()}: LogicalZone.{zone},')
    code.append('}')

    code.append('')
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(code))
    print(f"  [OK] Generated {out_file.relative_to(ROOT_DIR)}")

def generate_events():
    out_file = OUT_DIR / "events.py"
    code = [
        '"""',
        'AUTOGENERATED FILE — DO NOT EDIT DIRECTLY',
        'Generated from contracts/events/ by scripts/gen-python-types.py',
        '"""',
        '',
        'from __future__ import annotations',
        'from datetime import datetime',
        'from typing import Any, Dict, List, Optional',
        'from uuid import UUID',
        'from pydantic import BaseModel, ConfigDict, Field',
        'from .enums import WorkerEventType, WorkerState, LogicalZone',
        '',
        'class WorkerEvent(BaseModel):',
        '    """Canonical production-grade event envelope for all AI workforce events."""',
        '    model_config = ConfigDict(extra="ignore", populate_by_name=True)',
        '',
        '    event_id: UUID = Field(description="Globally unique identifier for this event")',
        '    event_type: WorkerEventType = Field(description="Closed enum event type")',
        '    schema_version: str = Field(default="1.0", description="Contract schema version")',
        '    organization_id: UUID = Field(description="Tenant isolation organization identifier")',
        '    mission_id: Optional[UUID] = Field(default=None, description="Mission identifier")',
        '    task_id: Optional[UUID] = Field(default=None, description="Worker task identifier")',
        '    parent_task_id: Optional[UUID] = Field(default=None, description="Parent task identifier")',
        '    worker_id: UUID = Field(description="Worker identifier")',
        '    worker_run_id: UUID = Field(description="Worker execution run identifier")',
        '    correlation_id: UUID = Field(description="Causation/operation correlation group")',
        '    causation_id: Optional[UUID] = Field(default=None, description="Event that caused this event")',
        '    trace_id: Optional[str] = Field(default=None, description="OpenTelemetry trace ID")',
        '    span_id: Optional[str] = Field(default=None, description="OpenTelemetry span ID")',
        '    source_connection_id: Optional[UUID] = Field(default=None, description="Source connection ID")',
        '    entity_id: Optional[UUID] = Field(default=None, description="World model entity ID")',
        '    product_id: Optional[UUID] = Field(default=None, description="Product ID")',
        '    logical_zone: Optional[LogicalZone] = Field(default=None, description="Logical zone in 3D HQ")',
        '    logical_station: Optional[str] = Field(default=None, description="Station identifier")',
        '    dedupe_key: Optional[str] = Field(default=None, description="Deduplication key")',
        '    idempotency_key: str = Field(description="Idempotency key for replay and duplicate rejection")',
        '    sequence: int = Field(ge=0, description="Monotonic sequence number per worker_run_id")',
        '    occurred_at: datetime = Field(description="Worker clock timestamp")',
        '    processed_at: Optional[datetime] = Field(default=None, description="Journal recorded timestamp")',
        '    payload: Dict[str, Any] = Field(default_factory=dict, description="Typed event payload")',
        '    metadata: Dict[str, str] = Field(default_factory=dict, description="Extensibility metadata")',
        '',
        '    def to_dict(self) -> Dict[str, Any]:',
        '        return self.model_dump(mode="json")',
        '',
        '# Payload Models for Specific Key Events',
        '',
        'class WorkerStartedPayload(BaseModel):',
        '    worker_type: str',
        '    worker_name: Optional[str] = None',
        '    autonomy_level: int = Field(ge=1, le=5)',
        '    mission_objective: str',
        '    budget: Optional[Dict[str, Any]] = None',
        '    assigned_products: List[UUID] = Field(default_factory=list)',
        '',
        'class WorkerStateChangedPayload(BaseModel):',
        '    from_state: WorkerState',
        '    to_state: WorkerState',
        '    reason: Optional[str] = None',
        '    task_type: Optional[str] = None',
        '    estimated_duration_seconds: Optional[int] = None',
        '',
        'class WorkerSourceOpenedPayload(BaseModel):',
        '    platform: str',
        '    source_name: str',
        '    source_station_id: Optional[str] = None',
        '    query: Optional[str] = None',
        '    query_type: Optional[str] = None',
        '    target_community: Optional[str] = None',
        '    reason: Optional[str] = None',
        '    expected_value: Optional[float] = None',
        '',
        'class WorkerProblemDetectedPayload(BaseModel):',
        '    problem_statement: str',
        '    problem_category: Optional[str] = None',
        '    confidence: float = Field(ge=0.0, le=1.0)',
        '    source_url: str',
        '    evidence_quote: Optional[str] = None',
        '    industry: Optional[str] = None',
        '    persona_signals: List[str] = Field(default_factory=list)',
        '    urgency: Optional[str] = None',
        '    problem_id: Optional[UUID] = None',
        '',
        'class WorkerProductMatchedPayload(BaseModel):',
        '    signal_summary: str',
        '    primary_product_id: UUID',
        '    primary_product_name: Optional[str] = None',
        '    secondary_product_id: Optional[UUID] = None',
        '    secondary_product_name: Optional[str] = None',
        '    cross_sell_product_id: Optional[UUID] = None',
        '    cross_sell_product_name: Optional[str] = None',
        '    overall_score: float = Field(ge=0.0, le=1.0)',
        '    match_components: Dict[str, float]',
        '    explanation: str',
        '    match_reasons: List[str] = Field(default_factory=list)',
        '    non_match_reasons: List[str] = Field(default_factory=list)',
        '    portfolio_match_id: Optional[UUID] = None',
        '',
        'class WorkerTaskTransferredPayload(BaseModel):',
        '    to_worker_id: Optional[UUID] = None',
        '    to_worker_type: str',
        '    to_worker_name: Optional[str] = None',
        '    task_type: str',
        '    task_id: UUID',
        '    from_zone: LogicalZone',
        '    to_zone: LogicalZone',
        '    package_contents: Dict[str, Any]',
        '    priority: str = "normal"',
        '    reason: Optional[str] = None',
        '',
        'class WorkerEvidenceFoundPayload(BaseModel):',
        '    claim_statement: str',
        '    evidence_type: str',
        '    source_url: str',
        '    source_timestamp: Optional[datetime] = None',
        '    evidence_quote: Optional[str] = None',
        '    confidence: float = Field(ge=0.0, le=1.0)',
        '    source_authority: Optional[float] = None',
        '    is_independent: bool = True',
        '    lineage_parent_url: Optional[str] = None',
        '    investigation_id: UUID',
        '    claim_id: Optional[UUID] = None',
        '    evidence_id: Optional[UUID] = None',
        '',
        'class WorkerApprovalRequestedPayload(BaseModel):',
        '    action_type: str',
        '    action_id: UUID',
        '    draft_content: str',
        '    reason_for_approval: str',
        '    risk_level: str = "medium"',
        '    target_entity: Optional[str] = None',
        '    target_platform: Optional[str] = None',
        '    product_context: Optional[str] = None',
        '    evidence_summary: Optional[str] = None',
        '    expires_at: Optional[datetime] = None',
        '',
        'class WorkerVerificationCompletedPayload(BaseModel):',
        '    claim_id: UUID',
        '    verdict: str',
        '    reason: str',
        '    checks_performed: Dict[str, bool] = Field(default_factory=dict)',
        '    contradiction_ids: List[UUID] = Field(default_factory=list)',
        '    new_confidence: Optional[float] = None',
        '    verification_id: Optional[UUID] = None',
        '',
        'class WorkerLearningUpdatedPayload(BaseModel):',
        '    learning_type: str',
        '    description: str',
        '    entity_type: Optional[str] = None',
        '    entity_id: Optional[UUID] = None',
        '    changes: List[str] = Field(default_factory=list)',
        '    triggered_by: Optional[str] = None',
        '    learning_event_id: Optional[UUID] = None',
    ]

    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(code))
    print(f"  [OK] Generated {out_file.relative_to(ROOT_DIR)}")

def main():
    print("Generating Python Pydantic models from contracts...")
    generate_enums()
    generate_events()
    print("Done generating Python models.")

if __name__ == "__main__":
    main()
