"""phase1 full domain schema

Revision ID: fec5f4418bca
Revises: 
Create Date: 2026-09-21 12:15:29.502346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec5f4418bca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('sources',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('default_rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_autonomy_level', sa.Integer(), nullable=False),
    sa.Column('default_zone', sa.String(length=50), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('default_budget', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_org_occurred', ['organization_id', 'occurred_at'], unique=False)

    op.create_table('competitor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('messaging', sa.JSON(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_profiles_organization_id'), ['organization_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_state'), ['state'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_organization_id'), ['organization_id'], unique=False)

    op.create_table('event_journal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('worker_run_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('causation_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('span_id', sa.String(length=100), nullable=True),
    sa.Column('source_connection_id', sa.String(length=36), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('logical_zone', sa.String(length=50), nullable=True),
    sa.Column('logical_station', sa.String(length=100), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('event_journal', schema=None) as batch_op:
        batch_op.create_index('ix_event_correlation', ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_causation_id'), ['causation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_journal_logical_zone'), ['logical_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_source_connection_id'), ['source_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_journal_worker_run_id'), ['worker_run_id'], unique=False)
        batch_op.create_index('ix_event_mission_occurred', ['mission_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_event_org_occurred', ['organization_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_event_worker_seq', ['worker_run_id', 'sequence'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('value_payload', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_subject_id'), ['subject_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('learning_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('learning_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('scheduled_cron', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index('ix_mission_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_missions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_missions_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_missions_status'), ['status'], unique=False)

    op.create_table('portfolio_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('competing_solutions', sa.JSON(), nullable=False),
    sa.Column('portfolio_coverage_score', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_gaps_opportunity_score'), ['opportunity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_gaps_organization_id'), ['organization_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_product_org_slug', ['organization_id', 'slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_organization_id'), ['organization_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)

    op.create_table('source_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_connections_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_connections_source_id'), ['source_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('worker_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('from_worker_id', sa.String(length=36), nullable=False),
    sa.Column('to_worker_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_messages_from_worker_id'), ['from_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_messages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_messages_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_messages_to_worker_id'), ['to_worker_id'], unique=False)

    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('worker_type_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('logical_zone', sa.String(length=50), nullable=False),
    sa.Column('logical_station', sa.String(length=100), nullable=True),
    sa.Column('current_mission_id', sa.String(length=36), nullable=True),
    sa.Column('current_task_id', sa.String(length=36), nullable=True),
    sa.Column('current_source', sa.String(length=100), nullable=True),
    sa.Column('current_url', sa.String(length=1000), nullable=True),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_type_id'], ['worker_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_current_mission_id'), ['current_mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_current_task_id'), ['current_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_logical_zone'), ['logical_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_worker_type_id'), ['worker_type_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_organization_id'), ['organization_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('competitor_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_events_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('crawl_frontier_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('intent_weight', sa.Float(), nullable=False),
    sa.Column('information_gain', sa.Float(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_frontier_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_source_connection_id'), ['source_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_frontier_items_state'), ['state'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_entity_id'), ['entity_id'], unique=False)

    op.create_table('fetched_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('rendered_content', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetched_resources', schema=None) as batch_op:
        batch_op.create_index('ix_fetched_resource_org_url', ['organization_id', 'url'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetched_resources_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetched_resources_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetched_resources_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetched_resources_source_connection_id'), ['source_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetched_resources_url'), ['url'], unique=False)

    op.create_table('investigation_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('answer_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_questions_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('target_username', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('problem_summary', sa.Text(), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('commercial_relevance', sa.Float(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_state'), ['state'], unique=False)

    op.create_table('mission_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_goals_mission_id'), ['mission_id'], unique=False)

    op.create_table('mission_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_runs_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_runs_status'), ['status'], unique=False)

    op.create_table('portfolio_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('primary_product_id', sa.String(length=36), nullable=False),
    sa.Column('secondary_product_id', sa.String(length=36), nullable=True),
    sa.Column('cross_sell_product_id', sa.String(length=36), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('problem_fit', sa.Float(), nullable=False),
    sa.Column('persona_fit', sa.Float(), nullable=False),
    sa.Column('industry_fit', sa.Float(), nullable=False),
    sa.Column('intent_fit', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('match_reasons', sa.JSON(), nullable=False),
    sa.Column('non_match_reasons', sa.JSON(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_matches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_matches_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_matches_primary_product_id'), ['primary_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_matches_signal_id'), ['signal_id'], unique=False)

    op.create_table('product_brains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('icp', sa.Text(), nullable=False),
    sa.Column('personas', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('problems_solved', sa.JSON(), nullable=False),
    sa.Column('problems_not_solved', sa.JSON(), nullable=False),
    sa.Column('product_boundaries', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('use_cases', sa.JSON(), nullable=False),
    sa.Column('integrations', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('semantic_concepts', sa.JSON(), nullable=False),
    sa.Column('customer_language', sa.JSON(), nullable=False),
    sa.Column('negative_keywords', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('proof_points', sa.JSON(), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('approved_claims', sa.JSON(), nullable=False),
    sa.Column('forbidden_claims', sa.JSON(), nullable=False),
    sa.Column('messaging_guidelines', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_brains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_brains_product_id'), ['product_id'], unique=True)

    op.create_table('product_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_features_product_id'), ['product_id'], unique=False)

    op.create_table('product_problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('target_segment', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_problems_product_id'), ['product_id'], unique=False)

    op.create_table('product_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_a_id', sa.String(length=36), nullable=False),
    sa.Column('product_b_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_a_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_b_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_product_rel_pair', ['product_a_id', 'product_b_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_relationships_product_a_id'), ['product_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relationships_product_b_id'), ['product_b_id'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('from_entity_id', sa.String(length=36), nullable=False),
    sa.Column('to_entity_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_from_entity_id'), ['from_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_relationship_type'), ['relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_to_entity_id'), ['to_entity_id'], unique=False)

    op.create_table('source_cursors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('last_item_id', sa.String(length=255), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_cursors', schema=None) as batch_op:
        batch_op.create_index('ix_source_cursor_unique', ['source_connection_id', 'topic'], unique=True)
        batch_op.create_index(batch_op.f('ix_source_cursors_source_connection_id'), ['source_connection_id'], unique=False)

    op.create_table('source_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('items_per_hour', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count_last_hour', sa.Integer(), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_health_source_connection_id'), ['source_connection_id'], unique=True)

    op.create_table('source_reliability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_reliability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_reliability_source_connection_id'), ['source_connection_id'], unique=True)

    op.create_table('worker_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('autonomy_level', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('pages_inspected', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_runs_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_runs_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_runs_worker_id'), ['worker_id'], unique=False)

    op.create_table('worker_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('worker_type_required', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.JSON(), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_tasks_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tasks_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_tasks_worker_id'), ['worker_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_entity', sa.String(length=255), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('policy_evaluation', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('contradictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('claim_a_id', sa.String(length=36), nullable=False),
    sa.Column('claim_b_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_a_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_b_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradictions_claim_a_id'), ['claim_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradictions_claim_b_id'), ['claim_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contradictions_organization_id'), ['organization_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('source_connection_id', sa.String(length=36), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_embedding', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['fetched_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_document_org_type', ['organization_id', 'document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_connection_id'), ['source_connection_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_authority', sa.Float(), nullable=False),
    sa.Column('is_independent', sa.Boolean(), nullable=False),
    sa.Column('lineage_parent_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_organization_id'), ['organization_id'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('checks_performed', sa.JSON(), nullable=False),
    sa.Column('verified_by_worker_id', sa.String(length=36), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_claim_id'), ['claim_id'], unique=False)

    op.create_table('worker_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('worker_run_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['worker_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_attempts_task_id'), ['task_id'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_run_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('current_url', sa.String(length=1000), nullable=True),
    sa.Column('task_summary', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_run_id'], ['worker_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_worker_run_id'), ['worker_run_id'], unique=False)

    op.create_table('worker_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_run_id', sa.String(length=36), nullable=False),
    sa.Column('llm_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('browser_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_run_id'], ['worker_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_metrics_worker_run_id'), ['worker_run_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_action_id'), ['action_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('engagement_metrics', sa.JSON(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_action_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_action_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('worker_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_metrics_worker_run_id'))

    op.drop_table('worker_metrics')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_worker_run_id'))
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_recorded_at'))

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('worker_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_attempts_task_id'))

    op.drop_table('worker_attempts')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_claim_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_claim_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_connection_id'))
        batch_op.drop_index(batch_op.f('ix_documents_resource_id'))
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))
        batch_op.drop_index('ix_document_org_type')

    op.drop_table('documents')
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradictions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_contradictions_claim_b_id'))
        batch_op.drop_index(batch_op.f('ix_contradictions_claim_a_id'))

    op.drop_table('contradictions')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_actions_lead_id'))

    op.drop_table('actions')
    with op.batch_alter_table('worker_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_tasks_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_tasks_type'))
        batch_op.drop_index(batch_op.f('ix_worker_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_worker_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_worker_tasks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_worker_tasks_mission_id'))

    op.drop_table('worker_tasks')
    with op.batch_alter_table('worker_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_runs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_worker_runs_mission_id'))

    op.drop_table('worker_runs')
    with op.batch_alter_table('source_reliability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_reliability_source_connection_id'))

    op.drop_table('source_reliability')
    with op.batch_alter_table('source_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_health_source_connection_id'))

    op.drop_table('source_health')
    with op.batch_alter_table('source_cursors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_cursors_source_connection_id'))
        batch_op.drop_index('ix_source_cursor_unique')

    op.drop_table('source_cursors')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_to_entity_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_relationships_organization_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_from_entity_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('product_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_relationships_product_b_id'))
        batch_op.drop_index(batch_op.f('ix_product_relationships_product_a_id'))
        batch_op.drop_index('ix_product_rel_pair')

    op.drop_table('product_relationships')
    with op.batch_alter_table('product_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_problems_product_id'))

    op.drop_table('product_problems')
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_features_product_id'))

    op.drop_table('product_features')
    with op.batch_alter_table('product_brains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_brains_product_id'))

    op.drop_table('product_brains')
    with op.batch_alter_table('portfolio_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_matches_signal_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_matches_primary_product_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_matches_overall_score'))
        batch_op.drop_index(batch_op.f('ix_portfolio_matches_organization_id'))

    op.drop_table('portfolio_matches')
    with op.batch_alter_table('mission_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_runs_status'))
        batch_op.drop_index(batch_op.f('ix_mission_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_mission_runs_mission_id'))

    op.drop_table('mission_runs')
    with op.batch_alter_table('mission_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_goals_mission_id'))

    op.drop_table('mission_goals')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_state'))
        batch_op.drop_index(batch_op.f('ix_leads_product_id'))
        batch_op.drop_index(batch_op.f('ix_leads_organization_id'))
        batch_op.drop_index(batch_op.f('ix_leads_conversation_id'))

    op.drop_table('leads')
    with op.batch_alter_table('investigation_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_questions_investigation_id'))

    op.drop_table('investigation_questions')
    with op.batch_alter_table('fetched_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetched_resources_url'))
        batch_op.drop_index(batch_op.f('ix_fetched_resources_source_connection_id'))
        batch_op.drop_index(batch_op.f('ix_fetched_resources_organization_id'))
        batch_op.drop_index(batch_op.f('ix_fetched_resources_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_fetched_resources_content_hash'))
        batch_op.drop_index('ix_fetched_resource_org_url')

    op.drop_table('fetched_resources')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_alias'))

    op.drop_table('entity_aliases')
    with op.batch_alter_table('crawl_frontier_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_state'))
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_source_connection_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_priority_score'))
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_organization_id'))
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_next_check_at'))
        batch_op.drop_index(batch_op.f('ix_crawl_frontier_items_dedupe_key'))

    op.drop_table('crawl_frontier_items')
    with op.batch_alter_table('competitor_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_events_detected_at'))
        batch_op.drop_index(batch_op.f('ix_competitor_events_competitor_id'))

    op.drop_table('competitor_events')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_conversation_id'))

    op.drop_table('comments')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_organization_id'))
        batch_op.drop_index(batch_op.f('ix_claims_investigation_id'))

    op.drop_table('claims')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_worker_type_id'))
        batch_op.drop_index(batch_op.f('ix_workers_status'))
        batch_op.drop_index(batch_op.f('ix_workers_organization_id'))
        batch_op.drop_index(batch_op.f('ix_workers_logical_zone'))
        batch_op.drop_index(batch_op.f('ix_workers_current_task_id'))
        batch_op.drop_index(batch_op.f('ix_workers_current_mission_id'))

    op.drop_table('workers')
    with op.batch_alter_table('worker_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_messages_to_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_messages_task_id'))
        batch_op.drop_index(batch_op.f('ix_worker_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_worker_messages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_worker_messages_from_worker_id'))

    op.drop_table('worker_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('source_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_connections_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_connections_organization_id'))

    op.drop_table('source_connections')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_signals_detected_at'))

    op.drop_table('signals')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_organization_id'))

    op.drop_table('roles')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index('ix_product_org_slug')

    op.drop_table('products')
    with op.batch_alter_table('portfolio_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_gaps_organization_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_gaps_opportunity_score'))

    op.drop_table('portfolio_gaps')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_status'))
        batch_op.drop_index(batch_op.f('ix_missions_priority'))
        batch_op.drop_index(batch_op.f('ix_missions_organization_id'))
        batch_op.drop_index('ix_mission_org_status')

    op.drop_table('missions')
    with op.batch_alter_table('learning_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_learning_events_created_at'))

    op.drop_table('learning_events')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_mission_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_subject_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_organization_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('event_journal', schema=None) as batch_op:
        batch_op.drop_index('ix_event_worker_seq')
        batch_op.drop_index('ix_event_org_occurred')
        batch_op.drop_index('ix_event_mission_occurred')
        batch_op.drop_index(batch_op.f('ix_event_journal_worker_run_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_worker_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_task_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_source_connection_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_product_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_organization_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_event_journal_mission_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_logical_zone'))
        batch_op.drop_index(batch_op.f('ix_event_journal_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_event_journal_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_journal_entity_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_event_journal_causation_id'))
        batch_op.drop_index('ix_event_correlation')

    op.drop_table('event_journal')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_name'))

    op.drop_table('entities')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_state'))
        batch_op.drop_index(batch_op.f('ix_conversations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_external_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('competitor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_profiles_organization_id'))

    op.drop_table('competitor_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('worker_types')
    op.drop_table('sources')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
